version: "3.8"

services:

  postgres:
    image: postgres:16
    container_name: cloudtask-postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: cloudtask

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data
    
    restart: unless-stopped

    networks:
    - cloudtask-network

  backend:
    build:
      context: ../../apps/backend

    container_name: cloudtask-backend

    ports:
      - "5000:5000"

    depends_on:
      - postgres

    environment:
      PORT: 5000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres123
      DB_NAME: cloudtask
      JWT_SECRET: cloudtask_super_secret_key_2026
      
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    
    restart: unless-stopped
    networks:
     - cloudtask-network

  frontend:
    build:
      context: ../../apps/frontend

    container_name: cloudtask-frontend

    ports:
      - "5173:80"

    depends_on:
      - backend

    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

    restart: unless-stopped

    networks:
     - cloudtask-network

volumes:
  postgres-data:

networks:
  cloudtask-network: