apiVersion: v1
kind: Secret

metadata:
  name: cloudtask-secret
  namespace: cloudtask

type: Opaque

stringData:
  DB_USER: postgres
  DB_PASSWORD: postgres123
  JWT_SECRET: cloudtask_super_secret_key_2026